# Generated by Django 3.2.5 on 2024-07-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaruselSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Նկար')),
            ],
            options={
                'verbose_name': 'Նկարների Սեկցիա',
                'verbose_name_plural': 'Նկարների Սեկցիա',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Վերնագիր')),
                ('icon_1', models.ImageField(upload_to='images/icon/', verbose_name='Նկար')),
                ('href_1', models.CharField(max_length=100, verbose_name='հղում')),
                ('icon_2', models.ImageField(upload_to='images/icon/', verbose_name='Նկար')),
                ('href_2', models.CharField(max_length=100, verbose_name='հղում')),
                ('tel', models.CharField(max_length=40, verbose_name='հեր')),
                ('email', models.CharField(max_length=100, verbose_name='մեիլ')),
            ],
            options={
                'verbose_name': 'Կոնտակտային սեկցիա',
                'verbose_name_plural': 'Կոնտակտային սեկցիա',
            },
        ),
        migrations.CreateModel(
            name='CourseConducted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Վերնագիր')),
            ],
            options={
                'verbose_name': 'Դասընթացը անցկացվել սեկցիա',
                'verbose_name_plural': 'Դասընթացը անցկացվել սեկցիա',
            },
        ),
        migrations.CreateModel(
            name='CourseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Վերնագիր')),
            ],
            options={
                'verbose_name': 'Դասընթացի ծրագրի սեկցիա',
                'verbose_name_plural': 'Դասընթացի ծրագրի սեկցիա',
            },
        ),
        migrations.CreateModel(
            name='EndOfCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Վերնագիր')),
            ],
            options={
                'verbose_name': 'Դասընթացի ավարտի սեկցիա',
                'verbose_name_plural': 'Դասընթացի ավարտի սեկցիա',
            },
        ),
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Վերնագիր')),
                ('sub_title', models.CharField(max_length=200, verbose_name='փոքր Վերնագիր')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Նկար')),
                ('bg_image', models.ImageField(upload_to='images/backgraund/', verbose_name='ֆոնի Նկար')),
            ],
            options={
                'verbose_name': 'Ինֆո Սեկցիա',
                'verbose_name_plural': 'Ինֆո Սեկցիա',
            },
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=50, verbose_name='լոգո')),
                ('first_link', models.CharField(max_length=100, verbose_name='առաջին լինկի անուն')),
                ('first_qordinate', models.IntegerField(verbose_name='կորդինատներ')),
                ('second_link', models.CharField(max_length=100, verbose_name='եկրորդ լինկի անուն')),
                ('second_qordinate', models.IntegerField(verbose_name='կորդինատներ')),
                ('three_link', models.CharField(max_length=100, verbose_name='երորդ լինկի անուն')),
                ('three_qordinate', models.IntegerField(verbose_name='կորդինատներ')),
            ],
            options={
                'verbose_name': 'Մենյու',
                'verbose_name_plural': 'Մենյու',
            },
        ),
        migrations.CreateModel(
            name='OfferSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Վերնագիր')),
            ],
            options={
                'verbose_name': 'Առաջարկի սեկցիա',
                'verbose_name_plural': 'Առաջարկի սեկցիա',
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Վերնագիր')),
                ('sub_title', models.CharField(max_length=200, verbose_name='փոքր Վերնագիր')),
                ('description_1', models.TextField(verbose_name='նկարագրություն')),
                ('description_2', models.TextField(verbose_name='նկարագրություն')),
                ('description_3', models.TextField(verbose_name='նկարագրություն')),
                ('description_4', models.TextField(verbose_name='նկարագրություն')),
                ('button', models.CharField(max_length=40, verbose_name='կնոպկա')),
            ],
            options={
                'verbose_name': 'Հատուկ առաջարկ սեկցիա',
                'verbose_name_plural': 'Հատուկ առաջարկ սեկցիա',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Անուն')),
                ('last_name', models.CharField(max_length=50, verbose_name='Ազգանուն')),
                ('phone', models.CharField(max_length=50, verbose_name='նկար')),
            ],
            options={
                'verbose_name': 'Օկտատեր',
                'verbose_name_plural': 'Օկտատեր',
            },
        ),
        migrations.CreateModel(
            name='MainStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='թվեր')),
                ('sub_title', models.CharField(max_length=200, verbose_name='փոքր Վերնագիր')),
                ('description', models.TextField(verbose_name='նկարագրություն')),
                ('courseconducted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='myapp.courseconducted', verbose_name='Դասընթացը անցկացվել կապ')),
                ('courseprogram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='myapp.courseprogram', verbose_name='Դասընթացի ծրագրի կապ')),
                ('endOfcourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='myapp.endofcourse', verbose_name='Դասընթացի ավարտի կապ')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='myapp.offersection', verbose_name='Առարջակի կապ')),
            ],
            options={
                'verbose_name': 'Միասնական Տեսակ',
                'verbose_name_plural': 'Միասնական Տեսակ',
            },
        ),
    ]
